/*
ANALYSE TEXTUELLE

Nous avons récupérer 100 tweets d'Elon Musk, et nous désirons effectuer une analyse sur ses messages.

A partir des données fournies (et non modifiables),
vous devez calculer et afficher les informations suivantes :

1 - Passez tout le texte en minuscule
2 - Supprimer les caractères spéciaux suivants : .,_?!“”>&
3 - Comptez le nombre de fois ou chaque mot apparait
4 - Affichez les 10 mots les plus utilisés
5 - Afichez les 5 mots les moins utilisés
5 - Affichez la liste des tag utilisés
6 - Affichez la liste des urls trouvées
*/

const tweets = [
	'Great meeting you! https://twitter.com/MKBHD/status/1030627360993947648 …',
	'NEW VIDEO - Talking Tech with Elon Musk! https://youtu.be/MevKTPN4ozw  - RT! pic.twitter.com/tB2jPDNoQs',
	'I am a business magnet',
	'Good times with @JoeRogan … https://m.youtube.com/watch?v=ycPr5-27vSI&feature=youtu.be&a= …',
	'Tesla 1st, 2nd & 3rd in August sales https://twitter.com/InsideEVs/status/1037484104915345410 …',
	'MORE UPDATES NOW IN - Monthly Plug-In Sales Scorecard https://insideevs.com/monthly-plug-in-sales-scorecard/ …',
	'Holy cow! @Tesla #Model3 Outsold All BMW Passenger Cars In US https://insideevs.com/tesla-model-3-outsold-bmw-passenger-cars/ …',
	'Will be on @JoeRogan at 9:30pm Pacific on Thursday',
	'We got our first  Tesla Model 3 in December 2017. It was so damn good, we got another one in February 18 for my son. Now, these two cars are so great that my wife went shopping for a new car last month, she considered almost everything out there but what did she buy? Model 3.pic.twitter.com/zQ9aaeorwz',
	'Forward hatch view of Dragon departing the @Space_Station earlier this month.pic.twitter.com/L1Kc5XI0G7',
	'"Track Mode left me literally shaking with adrenaline" @roadshow https://www.cnet.com/roadshow/news/testing-tesla-model-3-performance-new-track-mode/ …',
	'The world lost a great man in John McCain. He was an honorable, kind, brave and fundamentally decent human being. If only there were more such people in the world.',
	'Most people don’t realize that the cost of operating an electric vehicle is much lower than a gas car. Electricity is way cheaper than gas plus no oil changes, tune-ups,smog checks & other service costs.',
	'Staying Public https://www.tesla.com/blog/staying-public …',
	'This is actually real https://twitter.com/SpaceX/status/1033167462986997760 …',
	'Crew access arm installed at Launch Complex 39A in Florida; will serve as a bridge for @NASA astronauts to board Crew Dragon. pic.twitter.com/E9OXAOGWtQ',
	'This time, the vacuum tunnel will be a bit longer & SpaceX will provide some advance funding for student teams with most promising designs. Bonus award for all race pods that exceed half the speed of sound! https://twitter.com/Hyperloop/status/1032818998243520512 …',
	'The 2019 Hyperloop Pod Competition is coming next summer. Registration is open now → http://hyperloop.com    http://youtube.com/watch?v=AO0sPME3j2s …',
	'3 motors.\n10,000Nm of torque.\nTop speed of 250+ mph.\n\nThe 2020 Tesla Roadster is more like a fighter plane. #JayLenosGarage pic.twitter.com/LjgtMESQ8d',
	'Goal is to service your car wherever you are, quietly & quickly. No need to bring it to a Tesla service center.https://twitter.com/Tesla/status/1032706860359417856 …',
	'Turns out 80% of repairs can be done without visiting a service center – we’re doubling our Mobile Service Fleet globally this year pic.twitter.com/gW3dJKkYgA',
	'Love born in the brain is more spirited, doubtless, than true love, but it has only flashes of enthusiasm; it knows itself too well, it criticizes itself incessantly; so far from banishing thought, it is itself reared only upon a structure of thought.\nThe Red and The Black',
	'pic.twitter.com/Q9JE06lmWN',
	'Really makes me wanna buy Rice Krispies https://twitter.com/MattPotter/status/1031921389220098049 …',
	'Mind blown by learning just now that Snap, Crackle and Pop are terms taken from physics (they are the 4th, 5th and 6th time derivatives of position)... and as if that wasn’t enough, we were perilously close to having a bowl of Jerk in the morning. https://en.m.wikipedia.org/wiki/Snap,_Crackle_and_Pop … pic.twitter.com/zmscMpKvIO',
	'Read Eliot’s notes on The Waste Land https://en.m.wikipedia.org/wiki/The_Waste_Land …pic.twitter.com/uToAi4kBi1',
	'NEW VIDEO - Tesla Factory Tour with Elon Musk! https://youtu.be/mr9kK0_7x08  - RT!pic.twitter.com/NEt90rFzbu',
	'Super appreciate free concert for Tesla during this intense time! https://twitter.com/Tesla/status/1030662218138890240 …',
	'Thanks for visiting, Jack!  @thirdmanrecords pic.twitter.com/XprEyU8RvQ',
	'Model 3 review by Unbox ... https://youtu.be/nPH_I_klt-E  via @YouTube',
	'Defeating traffic is the ultimate boss battle',
	'Always exciting to see innovative ideas like the proposed Dugout Loop to @Dodgers Stadium that could help ease congestion on our roads and make our most iconic destinations more accessible to everyone. https://twitter.com/boringcompany/status/1029911363164884992 …',
	'The Boring Company is excited to announce Dugout Loop – a high-speed, zero-emissions, underground public transportation system, allowing fans to get from the Red Line to Dodger Stadium in under 4 minutes http://www.boringcompany.com/dugout',
	'The Boring Company is excited to announce Dugout Loop – a high-speed, zero-emissions, underground public transportation system, allowing fans to get from the Red Line to Dodger Stadium in under 4 minutes http://www.boringcompany.com/dugout',
	'Falcon 9 lands on the “Of Course I Still Love You” droneship and returns to port after delivering the Merah Putih satellite to geosynchronous transfer orbit. This mission marked the first re-flight of a Falcon 9 Block 5 rocket booster. http://instagram.com/p/Bmg3v4jlnCN/ pic.twitter.com/4l3vmIBLyM',
	"Hear from the five astronauts who will be the first fly @boeingspace's Starliner and @SpaceX's Crew Dragon to the International Space Station! pic.twitter.com/x3pn9aVHJw",
	'We are hosting student tours of the Hawthorne tunnel site for schools in LA County! Each tour can accommodate up to 30 students. Interested faculty (or students with a faculty sponsor!) can reach out to studenttours@boringcompany.com',
	'The first four @NASA astronauts who will fly aboard Crew Dragon visited the factory to meet employees today. http://instagram.com/p/BmcaC94l1Kz/ pic.twitter.com/oTVIx79HaU',
	'Model 3 traction testing on pure ice & snowhttps://twitter.com/Tesla/status/1028673766090399744 …',
	'Model 3 Performance testing in Alaska  pic.twitter.com/C0zDe7IRGu',
	'Great Q&A @defcon last night. Thanks for helping make Tesla & SpaceX more secure! Planning to open-source Tesla vehicle security software for free use by other car makers. Extremely important to a safe self-driving future for all.',
	'And thigh high socks with pockets for lipliner & cards',
	'Unis3x',
	'Paired with thigh-high sockboots',
	'What are your fav short shorts?',
	'S3XY',
	'Short shorts coming soon to Tesla merch',
	'.@defcon. hqr sz wut.',
	'99% of the US population is within 150 miles of a Supercharger https://twitter.com/Tgalleg/status/1027337126881329152 …',
	'When I first heard about Tesla destination charging, it sounded too good to be true. I’ve since changed my mind. @elonmusk my #69birthdaytour showed me how well thought out your charging grid really is! pic.twitter.com/6jPzd6cPZp',
	'Free trial of Autopilot for those who haven’t purchased it is starting to roll out. 14 days to decide if you want it or not #Model3 #Teslapic.twitter.com/PVou1sDtTF',
	"It appears that there's overwhelming support from @ElectrekCo readers for @elonmusk's plan to take @Tesla private: https://electrek.co/2018/08/08/tesla-tsla-shorts-elon-musk-board-evaluate/ … pic.twitter.com/6xdC42zGWj",
	'Tesla deliveries & AP hardware chart by @lexfridman at MITpic.twitter.com/6vZxKMcec2',
	'Investor support is confirmed. Only reason why this is not certain is that it’s contingent on a shareholder vote. https://twitter.com/Tesla/status/1026912973120462848 …',
	'Taking Tesla Private\n https://www.tesla.com/blog/taking-tesla-private?redirect=no …',
	'Def no forced sales. Hope all shareholders remain. Will be way smoother & less disruptive as a private company. Ends negative propaganda from shorts.',
	'Absolutely. Am super appreciative of Tesla shareholders. Will ensure their prosperity in any scenario.',
	'Shareholders could either to sell at 420 or hold shares & go private',
	'My hope is *all* current investors remain with Tesla even if we’re private. Would create special purpose fund enabling anyone to stay with Tesla. Already do this with Fidelity’s SpaceX investment.',
	'Good morning',
	'Am considering taking Tesla private at $420. Funding secured.',
	'#SpaceX wants to re-fly a Block 5 rocket for the first time tonight—the two-hour launch window opens at 1:18am ET Tuesday (5:18 UTC). https://arstechnica.com/science/2018/08/tonight-spacex-to-reuse-its-first-block-5-variant-of-the-falcon-9/ …',
	'Falcon 9 and Merah Putih are vertical on Pad 40 in Florida. Weather is 80% favorable for the two-hour launch window, which opens Tuesday, August 7 at 1:18 a.m. EST, 5:18 a.m. UTC. http://spacex.com/webcast pic.twitter.com/xT23Oaz7bu',
	'Dragon returned home yesterday after its second month-long stay at the @Space_Station. It’s now headed to port for a cargo handover to @NASA. http://instagram.com/p/BmE9Of_l-M-/ pic.twitter.com/EINH2xExP2',
	'.@jalopnik reviews Model 3 Performance https://jalopnik.com/2018-tesla-model-3-performance-heres-what-we-thought-1828067979 …',
	'That’s right provided the two Crew Dragon test flights go well. Hardware will def be ready. https://twitter.com/WorldAndScience/status/1025973435888021505 …',
	'SpaceX Will Be Ready to Transport Humans in April 2019, NASA Estimates https://www.universal-sci.com/headlines/2018/8/4/spacex-will-be-ready-to-transport-humans-in-april-2019-nasa-estimates …',
	'Not true. With three kids in the car you need to stop every three hours for bathroom and food anyway. Charging is not nearly the big deal everyone thinks it is.',
	'Glad you’re enjoying Model 3 & thanks for buying a Tesla! Major enhancements to Autopilot & fun games coming in a month with V9.0. https://twitter.com/Scobleizer/status/1026199248985972736 …',
	'Thanks @elonmusk and @Tesla for the best summer ever! https://www.facebook.com/501319654/posts/10156555358909655/ … my Model 3 brings me more joy than anything else I have owned in my 53 years on earth. 8,910 miles on our road trip! pic.twitter.com/7LHrb0MzFA',
	'Love The Handmaiden. Director also made original Korean Oldboy. https://m.youtube.com/watch?v=IkvHtfRAKNkp …',
	'Performance Model 3 review by @mattdebord https://www.businessinsider.com/tesla-model-3-performance-first-drive-2018-8 …',
	'Dang, turns out even Hitler was shorting Tesla stock … https://m.youtube.com/watch?v=wxEClGh6Mus …',
	'Still as true today as it was 6 years ago',
	'Squirrels … https://twitter.com/elonmusk/status/168060414398177281 …',
	'Do not search for purple squirrels! Giving them attention only makes them want to be more purple.',
	'Station teams from around the world polled “go” for Friday’s release of the @SpaceX #Dragon cargo craft and its splashdown in the Pacific Ocean. https://go.nasa.gov/2LVuiEi pic.twitter.com/bT0YL22GhA',
	'Tesla Grid Controller and Powerpacks optimize renewable energy across Samoa’s grid https://ts.la/2LT02ts pic.twitter.com/w2TpAAaHPx',
	'Gigafactory 1 battery production has reached an annualized run rate of ≈20 GWh - more kWh than all other carmakers combined pic.twitter.com/wFIB7E72rX',
	'Dragon and the @Space_Station passed over SpaceX headquarters and across the face of the Moon last weekend. After a month-long stay, Dragon will detach from the orbiting laboratory and return to Earth on August 3. http://instagram.com/p/Bl8xjJFFrHM/ pic.twitter.com/Gvm75nJQDy',
	'Please send examples of prior work when applying. Looking for max playability & creativity.',
	'If you’re into video game development, consider applying to Tesla. We want to make super fun games that integrate the center touch screen, phone & car irl.',
	'Some of best classic @Atari games coming as Easter eggs in Tesla V9.0 release in about 4 weeks. Thanks @Atari!',
	'Falcon 9 launches Iridium to orbit from Vandenberg Air Force Base https://www.instagram.com/p/Bl8M-mNAN3f/?utm_source=ig_twitter_share&igshid=18erh862v2fe1 …',
	'We’re adding a “party & camper mode” soon to S/3/X, so your car can maintain air flow, temp, selective lights, music & power devices for 48 hours or more while parked. Big batteries rock …',
	'Not having a big gas guzzler engine in front means there’s room for trunks in front & back, plus longer crumple zone for best safety of any midsize car https://twitter.com/Tesla/status/1024335091785289729 …',
	'It’s crazy how much stuff fits in a Model 3 https://twitter.com/AlguireTim/status/1023784314343804928 …',
	'We tried out a new delivery system using an enclosed trailer straight from factory to owner’s home, so super convenient & car arrives in pristine condition without wasting plastic wrap https://twitter.com/MichiganMan2007/status/1023774002915893248 …',
	'When @elonmusk hand delivers your #Teslamodel3  thanks to the #Tesla team for an unforgettable day!! pic.twitter.com/Xr4MI7x8TM',
	'https://m.youtube.com/watch?v=uFquLU8-SNI …',
	'8-bit floating point?',
	'Think once, Tweet twice [do it]',
	'0',
	'Nothing is both real & imaginary',
	'The future is accelerating https://twitter.com/_SianAbigail/status/943556624668643329 …',
	"It's been a busy year in artificial intelligence. From AI beating a world-class poker player to a humanoid in a Twitter battle with @elonmusk - here is everything you need to know http://www.wired.co.uk/article/what-happened-in-ai-in-2017 … @WiredUK",
	'https://twitter.com/MAKERSwomen/status/1022995840363913216 …',
	'Gwynne Shotwell, the COO of @SpaceX and the woman who makes @ElonMusk’s ambitious plans a reality, reflects on her long career in aerospace technology in this MAKERS exclusive.  @GwynneShotwell\n https://trib.al/8dsJgR7',
	'More photos from Falcon 9’s launch of Iridium-7 → http://flickr.com/spacex pic.twitter.com/JG0qyiajb7',
	'Worth another retweet. Hope Dan Neil returns to Twitter. He left due to relentless attacks from short-sellers, who constantly peddle fear, uncertainty & doubt about Tesla. Dan won the Pulitzer & is considered by many to be the best car critic in the world. https://twitter.com/tesla/status/1020012323606487041 …'
];

console.log(tweets.length);
